"""empty message

Revision ID: ba9887775754
Revises: 
Create Date: 2021-05-16 19:00:12.101679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9887775754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('bank_account_number', sa.String(length=120), nullable=True))
    op.add_column('host', sa.Column('bank_routing_number', sa.String(length=120), nullable=True))
    op.add_column('host', sa.Column('venmo_handle', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'venmo_handle')
    op.drop_column('host', 'bank_routing_number')
    op.drop_column('host', 'bank_account_number')
    # ### end Alembic commands ###
